
version: 2
updates:
	- package-ecosystem: "pip"
		directory: "/"
		schedule:
			interval: "weekly"
		target-branch: [ "rdm-11", "rdm-12" ]

	- package-ecosystem: "github-actions"
		directory: "/"
		schedule:
			interval: "weekly"

