- id: eslint
  name: eslint
  description: ''
  entry: eslint
  language: node
  types: [javascript]
  args: []
  require_serial: false
  additional_dependencies:
    - "@inveniosoftware/eslint-config-invenio@^2.0.0"
    - "@babel/core@^7.18.6"
    - "@babel/eslint-parser@^7.18.2"
    - "@babel/preset-react@^7.18.6"
    - "eslint@^8.0.0"
    - "eslint-config-prettier@^8.5.0"
    - "eslint-config-react-app@^7.0.1"
    - "eslint-friendly-formatter@^4.0.0"
    - "eslint-plugin-flowtype@^8.0.0"
    - "eslint-plugin-import@^2.26.0"
    - "eslint-plugin-jsx-a11y@^6.6.0"
    - "eslint-plugin-node@^11.1.0"
    - "eslint-plugin-prettier@^4.2.1"
    - "eslint-plugin-promise@^6.0.1"
    - "eslint-plugin-react@<7.33.0"
    - "eslint-plugin-react-hooks@^4.6.0"
    - "eslint-webpack-plugin@^2.5.0"
    - "js-yaml@^4.1.0"
    - "prettier@^2.7.1"
  minimum_pre_commit_version: '0'

# - id: prettier
#   name: Prettier wrapper
#   entry: prettier
#   language: node
#   files: \.(js|jsx|ts|tsx)$
#   args: ["--write", "--ignore-unknown"]
