- id: eslint
  name: eslint
  description: ''
  entry: eslint
  language: node
  'types': [javascript]
  args: []
  require_serial: false
  minimum_pre_commit_version: '0'

# - id: prettier
#   name: Prettier wrapper
#   entry: prettier
#   language: node
#   files: \.(js|jsx|ts|tsx)$
#   args: ["--write", "--ignore-unknown"]
