- id: eslint
  name: ESLint wrapper
  entry: eslint
  language: node
  files: \.(js|jsx|ts|tsx)$
  args: ["--fix"]

- id: prettier
  name: Prettier wrapper
  entry: prettier
  language: node
  files: \.(js|jsx|ts|tsx)$
  args: ["--write", "--ignore-unknown"]
